server:
  error:
    whitelabel:
      enabled: false
spring:
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://monos.cyt30p97bce6.ap-northeast-2.rds.amazonaws.com:3306/blog
    username: root
    password: 25884447
    driver-class-name: org.mariadb.jdbc.Driver

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    co.monos.blog: DEBUG